spring:
  application:
    name: EjemploSprintSecurityConJWT

  datasource:
    url: jdbc:postgresql://localhost:5432/ddbbJWT
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    client-id: hotel-service

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.add.type.headers": false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "*"
      group-id: grupo1
      auto-offset-reset: earliest

    listener:
      missing-topics-fatal: false

server:
  port: 9090

kafka:
  request:
    topic: topic_request
  reply:
    topic: topic_reply
